"""add provider_status fields and provider_guid index

Revision ID: 837810485062
Revises: 56fbe8b859a4
Create Date: 2026-03-20 20:58:53.077388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837810485062'
down_revision = '56fbe8b859a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_status_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dispatch_requests_provider_guid'), ['provider_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_requests_provider_guid'))
        batch_op.drop_column('provider_status_updated_at')
        batch_op.drop_column('provider_status')

    # ### end Alembic commands ###
