server {
    listen 80;
    server_name request.pdhc.se;

    http2 on;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/local/www/request.pdhc/gateway/acme;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name request.pdhc.se;

    http2 on;

    ssl_certificate /etc/letsencrypt/live/request.pdhc.se/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/request.pdhc.se/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:9060;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
