server {
    listen 80;
    server_name request.pdhc.se;

    http2 on;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/local/www/request.pdhc/gateway/acme;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
